name: xreshaper-dev
channels:
  - conda-forge
dependencies:
  - click
  - codecov
  - coverage
  - dask
  - distributed
  - netcdf4
  - numpy
  - pip
  - pytest
  - pytest-cov
  - python=3.6
  - xarray
  - zarr
  - git
  - pip:
      - pytest-xdist
