name: xreshaper-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - click
  - dask
  - distributed
  - netcdf4
  - numpy==1.15
  - pytest
  - pytest-cov
  - python=3.6
  - xarray==0.11.3
  - zarr
  